In [1]:
from neural_network import NeuralNetwork
import numpy as np
import struct

# read in mnist dataset
def read_idx(filename):
    with open(filename, 'rb') as f:
        zero, data_type, dims = struct.unpack('>HBB', f.read(4))
        shape = tuple(struct.unpack('>I', f.read(4))[0] for d in range(dims))
        array = np.fromstring(f.read(), dtype=np.uint8).reshape(shape)
        return array.reshape(array.shape[0],-1).T
        
def convert_to_multiclass(Y):
    '''
    Convert Y from shape(1 x m) to shape (10 x m)
    '''
    Y_list = []
    for each in Y[0,:]:
        this_Y = np.zeros((10,))
        this_Y[each] = 1
        Y_list.append(this_Y)
    
    multiclass = np.array(Y_list).T
    return multiclass


def show_numbers(data, start_idx, end_idx):
    side = np.int8(np.sqrt(data.shape[0]))
    for each in range(start_idx, end_idx):
        pixels = ((data[:,each].reshape(side,side) * 255).astype(np.uint8))
        plt.imshow(pixels, cmap=plt.cm.binary)
        plt.show()

In [2]:
train_X = read_idx('dataset/train_images_ubyte')
train_Y = read_idx('dataset/train_labels_ubyte')
test_X = read_idx('dataset/test_images_ubyte')
test_Y = read_idx('dataset/test_labels_ubyte')

print("Train shape:\nX: {}\nY: {}".format(train_X.shape,train_Y.shape))
print(train_Y[:,:5])

Train shape:
X: (784, 60000)
Y: (1, 60000)
[[5 0 4 1 9]]


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  # Remove the CWD from sys.path while we load stuff.


In [3]:
multiclass_train_Y = convert_to_multiclass(train_Y)
multiclass_test_Y = convert_to_multiclass(test_Y)

print(multiclass_train_Y[:,:5])

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
this = np.array([[0,5,3,10,3],
                 [3,2,1,11,4]])
np.argmax(this, axis=0)

array([1, 0, 0, 1, 1])

In [5]:
layer_dims = [train_X.shape[0],300,10]
nn = NeuralNetwork(layer_dims,init_method='he')
print(nn)

Layer 1:
	W.shape: (300, 784)
	b.shape: (300, 1)
	initialization method: he
	activation method: relu

Layer 2:
	W.shape: (10, 300)
	b.shape: (10, 1)
	initialization method: he
	activation method: sigmoid




In [6]:
costs = nn.train(train_X[:,:5000], multiclass_train_Y[:,:5000], optimizer='gd')

Cost after epoch 0/50: 13.815519557968774
Cost after epoch 1/50: 13.815519557968774
Cost after epoch 2/50: 13.815519557968774
Cost after epoch 3/50: 13.815519557968774
Cost after epoch 4/50: 13.815519557968774
Cost after epoch 5/50: 13.815519557968774
Cost after epoch 6/50: 13.815519557968774
Cost after epoch 7/50: 13.815519557968775
Cost after epoch 8/50: 13.815519557968774
Cost after epoch 9/50: 13.815519557968774
Cost after epoch 10/50: 13.815519557968774
Cost after epoch 11/50: 13.815519557968774
Cost after epoch 12/50: 13.815519557968774
Cost after epoch 13/50: 13.815519557968774
Cost after epoch 14/50: 13.815519557968774
Cost after epoch 15/50: 13.815519557968774
Cost after epoch 16/50: 13.815519557968774
Cost after epoch 17/50: 13.815519557968774
Cost after epoch 18/50: 13.815519557968774
Cost after epoch 19/50: 13.815519557968774
Cost after epoch 20/50: 13.815519557968774
Cost after epoch 21/50: 13.815519557968774
Cost after epoch 22/50: 13.815519557968774
Cost after epoch 23/5

In [7]:
nn.AL.shape

(10, 8)

In [8]:
train_predict = nn.predict(train_X)
NeuralNetwork.print_accuracy(train_predict, multiclass_train_Y, dataset_name="Train set")

test_predict = nn.predict(test_X)
NeuralNetwork.print_accuracy(test_predict, multiclass_test_Y, dataset_name="Test set")

(10, 60000)
Train set accuracy: 0.0%
(10, 10000)
Test set accuracy: 0.0%


In [ ]:
print(nn.AL.shape)

In [ ]:
this = np.array([[0,5,3,10,3],
                 [3,2,1,11,4]])
this[this == np.amax(this, axis=0)] = 100

In [ ]:
this

In [ ]:
train_predict[:10]

In [ ]:
multiclass_train_Y[:,:10]

In [ ]:
train_predict = nn.predict(train_X)
nn.AL[:,:3]